# Lab 2 Assigment

Import relevant modules

In [12]:
import torch
import torch.nn as nn
import scipy.io
from sklearn.model_selection import train_test_split

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [20]:
#Read dataset
pathname = '/content/drive/MyDrive/CZ3005 Lab 2/OQC.mat'
mat = scipy.io.loadmat(pathname)

In [15]:
#Print Data 
full_dataset = mat['data']
full_dataset

array([[0.39052473, 0.14779758, 0.1563981 , ..., 0.07962529, 0.92246927,
        2.        ],
       [0.39052473, 0.14779758, 0.1563981 , ..., 0.05367681, 0.92148159,
        2.        ],
       [0.5084938 , 0.14779758, 0.1563981 , ..., 0.05611241, 0.9204939 ,
        2.        ],
       ...,
       [0.54001505, 0.00982888, 0.77251185, ..., 0.05611241, 0.93135813,
        0.        ],
       [0.60664394, 0.00982888, 0.77251185, ..., 0.05658079, 0.93086416,
        0.        ],
       [0.7189506 , 0.00982888, 0.77251185, ..., 0.05658079, 0.93086416,
        0.        ]])

In [17]:
len(full_dataset)

2952

In [21]:
x, y = full_dataset, range(len(full_dataset))

In [24]:
train, test =train_test_split(x,test_size=0.3)

In [41]:
len(train[0])

49

In [46]:
train[1]

array([1.00000000e+00, 1.25227584e-01, 5.92417062e-01, 1.73166692e-03,
       3.33333333e-01, 4.44444444e-01, 3.33333333e-01, 4.28571429e-01,
       2.50000000e-01, 5.00000000e-01, 5.00000000e-01, 2.50000000e-01,
       3.50680457e-01, 9.94390612e-01, 8.28405238e-01, 6.36363636e-01,
       2.50000000e-01, 3.75000000e-01, 5.00000000e-01, 6.66666667e-01,
       2.50000000e-01, 7.35802733e-02, 3.06230179e-01, 1.00000000e+00,
       5.00000000e-01, 5.66666597e-01, 6.93769821e-01, 6.12662951e-01,
       3.87337049e-01, 9.26383373e-01, 8.88888889e-01, 3.34645780e-02,
       4.99809148e-02, 2.34315015e-01, 0.00000000e+00, 6.60280762e-03,
       4.61077844e-01, 6.16027345e-01, 2.20123041e-02, 7.06281807e-01,
       3.72549020e-02, 1.04872425e-01, 1.00000000e+00, 3.76520200e-05,
       1.25000000e-01, 2.40749387e-02, 2.40749387e-02, 9.26419727e-01,
       1.00000000e+00])

In [52]:
train[2063]

array([8.55983418e-01, 3.05787889e-02, 6.49289100e-01, 2.40927571e-03,
       5.55555556e-01, 5.55555556e-01, 4.44444444e-01, 5.71428571e-01,
       2.50000000e-01, 5.00000000e-01, 1.00000000e+00, 0.00000000e+00,
       3.28662831e-01, 9.95993193e-01, 7.73671079e-01, 1.00000000e+00,
       3.12500000e-01, 3.75000000e-01, 0.00000000e+00, 6.66666667e-01,
       5.00000000e-01, 8.98763509e-02, 3.06230179e-01, 6.66666667e-01,
       5.00000000e-01, 0.00000000e+00, 6.93769821e-01, 6.14525149e-01,
       3.85474851e-01, 9.10079244e-01, 1.00000000e+00, 9.90157519e-01,
       4.99809148e-02, 2.31498110e-01, 1.00000000e+00, 6.53771093e-01,
       4.68063872e-01, 6.35776681e-01, 5.06109585e-02, 8.72665502e-01,
       9.94117647e-01, 6.66705724e-01, 1.00000000e+00, 3.76520200e-05,
       1.25000000e-01, 5.47072579e-02, 5.47072579e-02, 9.10123649e-01,
       0.00000000e+00])

In [68]:
def splitXY(dataset):
  a0 = 0 #Normal
  a1 = 0 #Weaving
  a2 = 0 #Short Forming

  x = [] #The 48 parameters
  y = [] #Represents the state of molding

  for dataline in dataset:
    i = len(dataline)-1
    if (dataline[i]==0):
      a0+=1
    elif (dataline[i]==1):
      a1+=1
    elif (dataline[i]==2):
      a2+=1
    x.append(dataline[:-1])
    y.append(dataline[i])
  return x,y

In [69]:
x_train, y_train = splitXY(train)
x_test, y_test = splitXY(test)

In [73]:
print("Train Set: ", len(x_train))
print(y_train)
print("-----------------")
print("Test Set: ", len(y_train))
print(y_test)

Train Set:  2066
[2.0, 1.0, 0.0, 2.0, 1.0, 1.0, 1.0, 2.0, 2.0, 0.0, 0.0, 2.0, 1.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0, 1.0, 2.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 0.0, 2.0, 1.0, 2.0, 0.0, 0.0, 1.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 2.0, 1.0, 2.0, 0.0, 2.0, 1.0, 0.0, 1.0, 1.0, 0.0, 2.0, 2.0, 2.0, 2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 2.0, 0.0, 2.0, 0.0, 2.0, 2.0, 0.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 2.0, 2.0, 2.0, 2.0, 0.0, 1.0, 0.0, 2.0, 0.0, 2.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 2.0, 2.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0, 1.0, 1.0, 1.0, 0.0, 2.0, 2.0, 0.0, 0.0, 1.0, 2.0, 1.0, 2.0, 2.0, 0.0, 1.0, 2.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 1.0, 2.0, 1.0, 0.0, 1.0, 1.0, 1.0, 2.0, 0.0, 1.0, 1.0, 0.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0, 2.0, 0.0, 1.0, 2.0, 0.0, 1.0, 0.0, 1.0, 1.0, 2.

## Task 1

You are asked to build a three-layer feed-forward neural network to solve the monitoring problem of injection molding machine. 

Your implementation must be in Pytorch and executable in Google Colab environments. 

The proportion of training and testing samples is 70:30 where your model must deliver the  smallest  testing  error  possible.    

In  that  case,  you  need  to  select  the  number  of  nodes  of  hidden layers,  the  number  of  epochs,  the  learning  rates,  the  mini-batch  size,  etc.  that  lead  to  the  smallest testing error. 

In this assignment, you have to use the SGD optimizer as exemplified in the lab materials under the mini-batch update fashion. 

The evaluation metric here is the classification error. 

No feature selection is allowed here. 

In [30]:
batch_size = 100
n_iters = 3000
num_epochs = n_iters / (len(train) / batch_size)
num_epochs = int(num_epochs)

train_loader = torch.utils.data.DataLoader(dataset=train, 
                                           batch_size=batch_size, 
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test, 
                                          batch_size=batch_size, 
                                          shuffle=False)

In [2]:
class FeedforwardNeuralNetModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(FeedforwardNeuralNetModel, self).__init__()
        # Linear function
        self.fc1 = nn.Linear(input_dim, hidden_dim) 

        # Non-linearity
        self.sigmoid = nn.Sigmoid()

        # Linear function (readout)
        self.fc2 = nn.Linear(hidden_dim, output_dim)  

    def forward(self, x):
        # Linear function  # LINEAR
        out = self.fc1(x)

        # Non-linearity  # NON-LINEAR
        out = self.sigmoid(out)

        # Linear function (readout)  # LINEAR
        out = self.fc2(out)
        return out

In [31]:
input_dim = 28*28
hidden_dim = 100
output_dim = 10

model = FeedforwardNeuralNetModel(input_dim, hidden_dim, output_dim)

In [32]:
criterion = nn.CrossEntropyLoss()

In [33]:
learning_rate = 0.1

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)  

In [75]:
iter = 0
for epoch in range(num_epochs):
    for i, (x, y) in enumerate(train_loader):
        
        # Clear gradients w.r.t. parameters
        optimizer.zero_grad()

        # Forward pass to get output/logits
        outputs = model(x)

        # Calculate Loss: softmax --> cross entropy loss
        loss = criterion(outputs, y)

        # Getting gradients w.r.t. parameters
        loss.backward()

        # Updating parameters
        optimizer.step()

        iter += 1

        if iter % 500 == 0:
            # Calculate Accuracy         
            correct = 0
            total = 0
            # Iterate through test dataset
            for images, labels in test_loader:
                # Load images with gradient accumulation capabilities
                images = images.view(-1, 28*28).requires_grad_()

                # Forward pass only to get logits/output
                outputs = model(images)

                # Get predictions from the maximum value
                _, predicted = torch.max(outputs.data, 1)

                # Total number of labels
                total += labels.size(0)

                # Total correct predictions
                correct += (predicted == labels).sum()

            accuracy = 100 * correct / total

            # Print Loss
            print('Iteration: {}. Loss: {}. Accuracy: {}'.format(iter, loss.item(), accuracy))

ValueError: ignored

# Task 2

You are asked to study the effect of network structure: hidden nodes, hidden layers to the classification performance.  
That  is,  you  try  different  network  configurations  and  understand  the  patterns. 
Your experiments have to be well-documented in your Jupyter notebook file and your report. 
It has to cover different aspects of network configurations such as shallow network, wide network, deep network etc.

# Task 3

You are asked to study the effect of learning rates. 

As with Task 2, your experiments have to be well-documented. 
You need to give correct conclusion and give suggestion how learning rates should be set.  

This  includes  possible  adaptive  learning  rates  where  the  value  increases  or  decreases  as  the increase of epochs. 

# Task 4

You are asked to study the effect of mini-batch size. 

You can set mini-batch size to be 1 (stochastic gradient  descent),  N  (batch  gradient  descent)  or  any  other  size.  

The  most  important  aspect  is  to  be conclusive with your finding. 

The mini-batch size really depends on the problem size. 